### PR TITLE
[math] feat: add erc20-balance-of-if-own-erc721 strategy

### PR DESCRIPTION
**Pull request by andreanistico**
# ERC20 BalanceOf If Own ERC721 Strategy

This strategy return the following voting power:
- 0 if the address doesn't own any of the ERC721 NFTs in *nftAddress*
- *erc20Address*.balanceOf(address) if the address owns at least one of those NFTs.

## Accepted options

- **nftAddress:** ERC721 NFT address;

- **erc20Address:** ERC20 token address;

- **decimals:** Number of decimals in ERC20 token.

## Examples

```JSON
{
  "nftAddress": "0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb",
  "erc20Address": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  "symbol": "WETH",
  "decimals": 18
}
```

Example provided with *cryptoPunk* erc721 NFT's and *WETH* erc20 token's addresses

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @andreanistico Thanks for the PR but I feel like it is better to add a new operation to https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/math/README.md math strategy, so others can re-use this functionality quickly for other strategies too, Can you do it?

**Comment by ChaituVR** [comment]
Maybe something like `a-if-b-exists`

**Comment by andreanistico** [comment]
@ChaituVR you're right. In the new commits I deleted my strategy and added the operation `a-if-b-gt-0` in the math one. I also added a test case in the math examples.json file and it passes. Please review .

**Comment by andreanistico** [comment]
Oh wait, I just realized that this strategy could already be implemented with the `a-if-lt-b` math operation:

a-if-lt-b | 3 | (x, a, b) = x < b ? a : x
-- | -- | --

that could be implemented like this:

(0, erc20-balance-of, erc721) = 0 < erc721 ? erc20-balance-of : 0

**Review by ChaituVR — APPROVED** [review]
Looks good

**Comment by ChaituVR** [comment]
Oh yes, Thanks for noticing this :) i didn't realize too 
> that could be implemented like this:

> (0, erc20-balance-of, erc721) = 0 < erc721 ? erc20-balance-of : 0

**Comment by ChaituVR** [comment]
Ok closing this then! Thanks for finding it out @andreanistico 👍 ❤️

**Pull request closed without merging**
