### PR TITLE
[erc20-balance-of-erc721-holders] Add strategy with ERC20 token balance voting power if holding ERC721

### PR DESCRIPTION
**Pull request by mitesh-mutha**
Changes proposed in this pull request:
- Add strategy with ERC20 token balance voting power if holding ERC721. This strategy assigns voting power to holders of particular ERC721 tokens. The voting power is based on the balances of a specific ERC20 token.

strategy

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hey @mitesh-mutha  I think `math` strategy will work in your case, plz try and let me know if it works.

**Comment by mitesh-mutha** [comment]
Hey @ChaituVR thanks for the title update and your comment! 

I checked out the `math` strategy. I don't think I can use that, since I need to check if someone is a holder of the `ERC721`. I don't care what their `ERC721` balance is. In this case I cannot take the `erc721` balance and `multiply` (in the `math` strategy) with `erc20 balance`. I don't see how I can make it work. 

What I have implemented is more of a gated community voting with erc721 being the "admission criteria" and erc20 being the voting power. 

Let me know what your thoughts are and how I can go about it. Thanks!

**Comment by ChaituVR** [comment]
@mitesh-mutha It should work with something like this 
https://snapshot.org/#/playground/math?query=eyJwYXJhbXMiOnsic3ltYm9sIjoiTUFUSCIsIm9wZXJhbmRzIjpbeyJ0eXBlIjoic3RyYXRlZ3kiLCJzdHJhdGVneSI6eyJuZXR3b3JrIjoiMSIsIm5hbWUiOiJlcmM3MjEiLCJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4MzMzN2RhYzlGMjUxZDRFNDAzRDYwMzBFMThlM2NmQjZhMmNiMTMzMyJ9fX0seyJ0eXBlIjoic3RyYXRlZ3kiLCJzdHJhdGVneSI6eyJuZXR3b3JrIjoiMSIsIm5hbWUiOiJlcmMyMC1iYWxhbmNlLW9mIiwicGFyYW1zIjp7ImFkZHJlc3MiOiIweEY3ZGVGMUQyRkJEQTZCNzRiZUU3NDUyZmRmNzg5NERhOTIwMTA2NWQiLCJkZWNpbWFscyI6MTh9fX0seyJ0eXBlIjoiY29uc3RhbnQiLCJ2YWx1ZSI6MX1dLCJvcGVyYXRpb24iOiJhLWlmLWd0ZS1iIn0sIm5ldHdvcmsiOiIxIiwic25hcHNob3QiOjE0OTI3NTYwLCJhZGRyZXNzZXMiOlsiMHgwNGYyYmE1NjdjMzc4YzZhODYwNzJlNjEwNzk2M2U4MGM4YTZhYWM0IiwiMHgwNWE0NDQ4NTk3OTM1YzUwOGU0YWQwZDJjZjU2ZDU2YmVkYjI0NmNlIl19

Try and let me know :)

**Comment by ChaituVR** [comment]
Awesome then :) closing this for now, feel free to reopen if needed.

**Pull request closed without merging**
