### PR TITLE
[immutable-x] remove immutable x from snapshot strategies

### PR DESCRIPTION
**Pull request by alexi21**
Remove immutable-x from snapshot strategies

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @alexi21 PR should be coming from `immutable`'s github as they are author of the strategy, Thanks

**Comment by alexi21** [comment]
Hi @ChaituVR that fork has been deleted, is it necessary to recreate or can we merge this one? Thank you

**Comment by alexi21** [comment]
Hi @ChaituVR we have deprecated snaphots and are now removing them. I can have someone else from the team give this a thumbs up. Appreciate your concern :)

**Comment by shineli1984** [comment]
👋 @ChaituVR Yes. Immutable intends to remove this snapshots.

**Comment by ChaituVR** [comment]
Looks like `immutablex.eth` space is still using it, if you are a admin/had contact with them, could you change the strategy to different one there first? else it may break few things.

**Comment by alexi21** [comment]
Hi 👋  @ChaituVR we are following up on this. We will delete the space asap and I will get back to you.
Thank you

**Comment by alexi21** [comment]
Hi @ChaituVR this should be good to go now

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
