### PR TITLE
Add offchain-delegation-2 Strategy for pre-distribution tokens

### PR DESCRIPTION
**Pull request by alexotsu**
This Strategy pulls token allocation information from a CSV. Necessary for temp checks that happen before distribution events.

Changes proposed in this pull request:
- Add `/offchain-delegation-2` containing example.json, index.ts, and README.md
- Update index.ts to include `offchain-delegation-2` as `offchainDelegation2`

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @alexotsu I don't understand the changes, it is same as offchain-delegation strategy but you are not reading scores of delegations?

**Comment by alexotsu** [comment]
> Hi @alexotsu I don't understand the changes, it is same as offchain-delegation strategy but you are not reading scores of delegations?

@ChaituVR yes - it is for tokens that haven’t been distributed to individual wallets yet for various reasons, but where projects still want to hold a vote. So the voting power itself is written down off-chain on the spreadsheet.

**Comment by ChaituVR** [comment]
Thank you! Can rename it to something else? :) because it may confuse many others with delegation strategy

**Comment by alexotsu** [comment]
Actually, I just realized that this is identical to the “[spreadsheet](https://github.com/snapshot-labs/snapshot-strategies/tree/master/src/strategies/spreadsheet)” strategy, so will plan to close unless you think there is some big reason to keep both

**Pull request closed without merging**
