### PR TITLE
[swapr] Implement custom strategy for Swapr governance

### PR DESCRIPTION
**Pull request by luzzif**
This initial implementation assigns scores to users based on their direct SWPR balance and based on their LP'd SWPR (even if the resulting LP tokens have been staked on Swapr farms).

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi, @luzzif as discussed in discord we are having issues with the Arbitrum node and won't be able to test this until then :) 

https://github.com/snapshot-labs/snapshot.js/issues/382

**Comment by ChaituVR** [comment]
@luzzif we now support Arbitrum on snapshot, are you still interested in this strategy??

If yes, there is an issue, it fails when 500 addresses are passed, try running `npm test --strategy=swapr --more=500` in your local

**Comment by luzzif** [comment]
Thanks for the heads up. I've actually just tried to run the test for the strategy, and it fails because Alchemy returns a `Queries more than 30 blocks behind `latest` are currently not supported on Arbitrum` error.

**Comment by ChaituVR** [comment]
@luzzif Actually the node is changed now, to get an updated node, try removing node_modules folder and run npm install again

**Comment by luzzif** [comment]
Oh my bad, sorry. I've now updated the strategy and it should be working!

**Review by bonustrack — APPROVED** [review]

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
@luzzif Thanks for your patience, https://snapshot.org/#/strategy/swapr is live now 👍

**Pull request merged**
