### PR TITLE
Add strategy for SuperBoring [superboring] 

### PR DESCRIPTION
**Pull request by d10r**
Adds a strategy for the SuperBoring DCA protocol.
For more information, see https://docs.superboring.xyz

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
Hi @d10r Some tests are failing, can try to run `yarn test --strategy=superboring` in your local?

**Comment by d10r** [comment]
Hi @ChaituVR , thx for the feedback.
I had everything green locally, need to run `yarn test --strategy=superboring --more=500` to include the failing test.
I don't currently have a simple fix, but will figure out something and update the PR.

**Comment by ChaituVR** [comment]
It looks like it timeout when we pass more addresses, should be fine I think

**Comment by d10r** [comment]
ok thx!

**Pull request merged**
