### PR TITLE
[delegate-registry-v2] Add optional v1 support

### PR DESCRIPTION
**Pull request by manboy-eth**
Adds optional support for "delegate registry v1" delegations in the "delegate registry v2" strategy.

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
Thanks @manboy-eth some test cases still fail 🙈 can take a look? Looks like no address in examples is returning a positive score
image

**Comment by ChaituVR** [comment]
image
Can also add some addresses that have voting power at the `latest` block  🙈 I tried but couldn't find them

**Comment by manboy-eth** [comment]
> image Can also add some addresses that have voting power at the `latest` block 🙈 I tried but couldn't find them

Aha, yes this is a problem :/ 
I can not easily make that test pass because there are no v2-delegations for the yam.eth context/space on mainnet or gnosis chain, and the yam.eth space does not have the delegate-registry-v2 strategy with v1 delegations enabled (via the `delegationV1VChainIds` strategy pram).

Making this test pass requires one of the following conditions:
1. The delegate-registry-v2 strategy is enabled on the space, and an address holding the token that is used in that space needs to delegate to another address on the mainnet or gnosis chain.
2. The delegate-registry-v2 strategy is enabled on the space, and the delegationV1VChainIds param set (to for instance, `[1, 100]`) on the mainnet or gnosis chain.

**Comment by ChaituVR** [comment]
Is it possible for you to create a test pass to test?

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
