### PR TITLE
[dappnode-dao] Add dappnode-dao strategy

### PR DESCRIPTION
**Pull request by dapplion**
Adds dappnode-dao strategy:

- 3 unipool contracts in target network: 2 with LP token, 1 with same token
- 1 unipool contract in xDAI with same token

### CODE REVIEW

**Comment by ChaituVR** [comment]
@dapplion there is some error while running the strategy:

```
Test strategy "dappnode-dao" › Strategy should run without any errors

    call revert exception (method="totalSupply()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.1)

      731 |                 case 2:
      732 |                     _a = _b.sent(), res = _a[1];
    > 733 |                     return [2 /*return*/, res.map(function (call, i) { return itf.decodeFunctionResult(calls[i][1], call); })];
          |                                                                                   ^
      734 |                 case 3:
      735 |                     e_2 = _b.sent();
      736 |                     return [2 /*return*/, Promise.reject(e_2)];

```

**Comment by ChaituVR** [comment]
Hey @dapplion, I think the error is because your fork branch is outdated from the master branch (many big changes pushed recently), can you please update your branch with those, that should fix this weird issue :)

**Review by ChaituVR — CHANGES_REQUESTED** [review]
@dapplion this strategy works for you in your local? Im getting this error
```
    call revert exception (method="totalSupply()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.1)
```

try running `npm run test --strategy=dappnode-dao` and make sure all test cases are passing,
I think we are getting this error from `unipoolUniv2LpStrategy` which is being used in this strategy, maybe something is not being passed correctly, please check :) Thanks

**Comment by dapplion** [comment]
> @dapplion this strategy works for you in your local? Im getting this error
> 
> ```
>     call revert exception (method="totalSupply()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.1)
> ```
> 
> try running `npm run test --strategy=dappnode-dao` and make sure all test cases are passing,
> I think we are getting this error from `unipoolUniv2LpStrategy` which is being used in this strategy, maybe something is not being passed correctly, please check :) Thanks

Thanks for looking into it! I've been debugging the strategy but I don't see why the multicall fails. I can call totalSupply() on the conctract individually but though your script's multicall it reverts. Have you encounter issues like this in the past?

**Review by rude69 — APPROVED** [review]

**Comment by ChaituVR** [comment]
@dapplion Closing this for now, please feel free to reopen this/to add a new strategy :) Thanks

**Comment by dapplion** [comment]
Thanks, DAppNode dao just uses a multichain strategy right now so this one is not necessary anymore, props to the nice modular design :+1:

**Comment by ChaituVR** [comment]
> Thanks, DAppNode dao just uses a multichain strategy right now so this one is not necessary anymore, props to the nice modular design 👍

@dapplion Cool then thank you :)

**Pull request closed without merging**
