### PR TITLE
[Decentral Games] Decentral Games Strategy

### PR DESCRIPTION
**Pull request by SatoshiNaoki**
Strategy for Decentral Games added

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @SatoshiNaoki This looks equal to `multichain` strategy. why not use it instead?

**Comment by SatoshiNaoki** [comment]
> Hi @SatoshiNaoki This looks equal to `multichain` strategy. why not use it instead?

for some contracts, voting power should be x1000.
I was going to do it by setting decimals as 15 instead of 18, but it seems it's not good.
so I just updated the calculation

**Comment by ChaituVR** [comment]
Hi @SatoshiNaoki 

> for some contracts, voting power should be x1000.
I was going to do it by setting decimals as 15 instead of 18, but it seems it's not good.
so I just updated the calculation

Which line is this change? I see it is the same as multichain? 🤔 
Do you mean in examples.json? if so you can change the params from your space settings directly

**Comment by ChaituVR** [comment]
Closing this as multichain strategy works for you. feel free to reopen if needed

**Pull request closed without merging**
