### PR TITLE
[vote-power-and-share] Vote power and share strategy

### PR DESCRIPTION
**Pull request by jinanton**
Feature # .

Changes proposed in this pull request:
-  added new strategy (`vote-power-and-share`) for get Voting power or Share of total supply depending on the parameters used

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Please revert changes from yarn.lock

**Comment by ChaituVR** [comment]
@jinanton

**Comment by jinanton** [comment]
> @jinanton

**Comment by jinanton** [comment]
> Please revert changes from yarn.lock

Ok, 10 minutes

**Review by bonustrack — COMMENTED** [review]
Can you run the "lint" script?

**Review by bonustrack — APPROVED** [review]

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
