### PR TITLE
[aavegotchi-agip] fix missing gotchi data with other endpoint

### PR DESCRIPTION
**Pull request by candoizo**
Fixes issue with missing gotchi data, we are aware of open proposals and still request the update be made. thanks

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hey @candoizo i get this error with latest snapshot

```
    Errors found in subgraphRequest: https://api.thegraph.com/subgraphs/name/aavegotchi/aavegotchi-core-matic[{"locations":[{"column":6,"line":1}],"message":"Unexpected `end of input`\nExpected `{`, `Name`, `(`, `$`, `:`, `=` or `)`"}]
```

**Comment by candoizo** [comment]
oh, the filter for `Object.entries(res).length > 0` on that query which seemed to fix it in my tests even when using the more flag but I will try another way. now it will succeed, thanks @ChaituVR

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
@candoizo Just waiting for one more PR to be merged before this going live, will update you once this change go live ;)

**Comment by ChaituVR** [comment]
@candoizo Changes should be live now, Thanks for waiting :)

**Pull request merged**
