### PR TITLE
Replace duplicate code with snapshot.js

### PR DESCRIPTION
**Pull request by ChaituVR**

### CODE REVIEW

**Comment by bonustrack** [comment]
@ChaituVR Looks good, i see there is still networks.json on the branch, can you remove it too?

**Comment by bonustrack** [comment]
Also can you move `SNAPSHOT_SUBGRAPH_URL` const from utils.ts to the file where it's being used?

**Comment by ChaituVR** [comment]
@bonustrack Done removed and moved ✔️

**Review by bonustrack — APPROVED** [review]
Looks good!

**Pull request merged**
