### PR TITLE
[planet-finance-v2] UPDATE: VOTING STRATEGY

### PR DESCRIPTION
**Pull request by ash-greninja-poke**
Fixes # .

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @ash-greninja-poke This change may affect the open proposal https://snapshot.org/#/planetfinance.eth/proposal/0x0675c87406eb068d59c1fedf2e439dd22759bf04d10dc6b40bfc974ec64210ed

If should not be effected, i would suggest you to create a `-v2` strategy

**Comment by ash-greninja-poke** [comment]
ok @ChaituVR will create it thanks.

**Comment by ChaituVR** [comment]
Or if we can wait until the proposal is closed `Feb 28, 2022, 12:30 PM` that should be fine too.

**Review by ChaituVR — CHANGES_REQUESTED** [review]
@ash-greninja-poke There are still changes in v1

**Pull request closed without merging**
