### PR TITLE
add support for ebisusbay membership [ebisus-members]

### PR DESCRIPTION
**Pull request by nschwermann**
Fixes # .

Changes proposed in this pull request:
-  Add support for EbisusBay memberships

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @nschwermann I think you can use the `contract-call` strategy with the `math` strategy and `min` operation for this. can try?

**Comment by nschwermann** [comment]
Hey @ChaituVR you mean to say this PR won't be necessary at all I can use those existing strategies or that I should extend/use them?

**Comment by nschwermann** [comment]
Hmm ok... It is complaining about undefined param of scores, not sure what that is but I can investigate it. Can close this ticket in the meantime.

**Comment by ChaituVR** [comment]
@nschwermann Just in case if it is still troubling you can post a message on our discord https://snapshot.discord.org

**Pull request closed without merging**
