### PR TITLE
Add delegation capabilities to OGN snapshot

### PR DESCRIPTION
**Pull request by sparrowDom**
Existing `ogn` strategy has created a snapshot according to its specific logic. This PR adds the ability to take delegated scores into account as well.

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @sparrowDom You can use `delegation` strategy in your space, resulting voting power will be VP of ogn + VP of delegaton

**Comment by ChaituVR** [comment]
Or you can pass your strategy into delegation strategy params

**Comment by sparrowDom** [comment]
nice @ChaituVR thank you. Have added the delegation strategy into our space and with the `strategies` portion of the JSON only containing our original `ogn` strategy params. So currently we have `ogn` & `delegation` strategies configured [in our space](https://snapshot.org/#/origingov.eth/settings). 

Before closing this PR could you just confirm please if that is all that is required? No additional configuration needed for the delegation strategy to only delegate the scores when delegators do not vote?

**Comment by ChaituVR** [comment]
@sparrowDom Correct, I suggest you to run a test proposal to make sure things are as you expected

**Comment by sparrowDom** [comment]
Got it thanks for all the help @ChaituVR

**Pull request closed without merging**
