### PR TITLE
[mcb-balance-from-graph] Fix graph query failed caused by mixed-cases address

### PR DESCRIPTION
**Pull request by yangzhao28**
Fixes the graph query failed caused by mixed-cases addresses.

### CODE REVIEW

**Comment by yangzhao28** [comment]
By the way, I found that the two requests sent by loading and verifing are exactly the same but the addresses in the response are lowercased and mixed-case respectively.

**Comment by ChaituVR** [comment]
@yangzhao28 try to use below function:
```js
import { getAddress } from '@ethersproject/address';
const checksumedAddress = getAddress(address);
```
using this you can convert an address into a checksummed address, we should not get lower cased addresses in the output

**Comment by yangzhao28** [comment]
> @yangzhao28 try to use below function:
> 
> ```js
> import { getAddress } from '@ethersproject/address';
> const checksumedAddress = getAddress(address);
> ```
> 
> using this you can convert an address into a checksummed address, we should not get lower cased addresses in the output

Thanks. I didn't change the addresses passed by arguments. The lowercased addresses are only used to query graph and match the query result.  In this case, should I still use the `getAddress` ?

**Comment by ChaituVR** [comment]
Oh then i think it is not required @yangzhao28 :)

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
