### PR TITLE
[hopr-staking-s2] Hopr staking v2

### PR DESCRIPTION
**Pull request by QYuQianchen**
This strategy returns the sum of rewards and the amount of tokens staked in the HOPR Staking program **season 2.**

actual staking
rewards - claimed rewards

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @QYuQianchen It is taking too much time when we pass more addresses into the strategy, try running 

```
yarn test --strategy=hopr-staking-s2 --more=500
```

**Comment by QYuQianchen** [comment]
Thank you @ChaituVR for the feedback. Could you please give another try? I made some changes and here is what I got:

image

**Comment by ChaituVR** [comment]
Hi @QYuQianchen Somehow it still fails with latest snapshot, i get this error:

```
Test strategy "hopr-staking-s2" with latest snapshot › Strategy should run without any errors

    TypeError: Cannot read properties of undefined (reading 'map')

      47 |     const data = await (0, utils_1.subgraphRequest)(HOPR_STAKING_SUBGRAPH_URL, query);
      48 |     // map result (data.accounts) to addresses
    > 49 |     const entries = data.accounts.map((d) => [
         |                                   ^
      50 |         d.id,
      51 |         bignumber_1.BigNumber.from(d.actualStake).add(bignumber_1.BigNumber.from(d.unclaimedRewards))
      52 |     ]);

      at stakingSubgraphQuery (dist/strategies/hopr-staking-s2/index.js:49:35)
          at async Promise.all (index 0)
      at Object.strategy (dist/strategies/hopr-staking-s2/index.js:65:34)
      at callStrategy (dist/utils.js:13:19)
          at async Promise.all (index 0)
      at Object.getScoresDirect (dist/utils.js:26:16)
      at Object.<anonymous> (test/index.spec.ts:108:14)

      ```

**Comment by QYuQianchen** [comment]
Hey @ChaituVR. Could you spare sometime to check it again? We have a voting schedule in <5 hours. Thank you very much!

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
