### PR TITLE
Improvement and more options to LRC L2 NFT balance strategy [lrc-l2-nft-balance-of]

### PR DESCRIPTION
**Pull request by curtis741**
adding options for blacklisting nft id's and filter by token id(s) instead of minter account id

Changes proposed in this pull request:
- Improve filter of NFT's by add tokens as a parameter to be an alternative to minter account id
- Improve blacklisting by add blacklisted_nft_id's so mismints or any other nft can be excluded from the result set

### CODE REVIEW

**Comment by ChaituVR** [comment]
@Karamorf  Can confirm this change? Also make sure there are no open proposals in your space

**Comment by ChaituVR** [comment]
@curtis741 Looks like there are conflicts. would be great if you can resolve

**Comment by curtis741** [comment]
@ChaituVR huh, I swore I pulled from master before starting this branch but I guess not. conflicts resolved.

Yes, this changes are to help support a couple requests from others that wanted to use this strategy. It should be entirely backward compatible. Also haven't even made my space yet so no worries on open proposals :)

**Review by ChaituVR — APPROVED** [review]
Thanks for resolving @curtis741 yea there are new strategies that are merged in between so that cause it :) so I see this PR is coming from @Karamorf Repo. so should be fine. merging it 🚀

**Pull request merged**
