### PR TITLE
Update MinotaurMoney voting strategy [minotaur-money]

### PR DESCRIPTION
**Pull request by pepperstepper**
Fixes # .

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by pepperstepper** [comment]
Is there an easy way to find out the current snapshot index for a chain i.e. cronos? Wanted to update the example.json too

**Comment by ChaituVR** [comment]
Hey, @pepperstepper what is the `current snapshot index` 🤔 you mean to get the latest block of Cronos?

**Comment by pepperstepper** [comment]
> Hey, @pepperstepper what is the `current snapshot index` 🤔 you mean to get the latest block of Cronos?

Hi, I was under impression the snapshots where taken on specific blocknumbers and you couldnt just put any one in there.

Maybe they changed it? Or maybe I was mistaken last time I did this. I thought trying random genuine ones didn't last time, but it seems to have worked this time!

Updated the PR with that, we would appreciate it if this could be merged,
Thank you very much!

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Can update version to `export const version = '0.0.4';` plz :)

**Comment by ChaituVR** [comment]
@pepperstepper also looks like test cases are failing because it is taking more than 10 secs to resolve. can you check on that?

**Comment by pepperstepper** [comment]
Hi,
It seems to be intermittent, for me it fails 1/5 runs or so. due to being over 10 seconds. Perhaps the cronos rpc is a bit on the slow side occasionally?

**Comment by pepperstepper** [comment]
There are 5 rpc calls per address (last I checked this was within the standard for PRs) and the rest of the logic should not be using much tine.

**Comment by pepperstepper** [comment]
> There are 5 rpc calls per address (last I checked this was within the standard for PRs) and the rest of the logic should not be using much tine.

Actually should be less than this as makeMulticaller is used

**Comment by pepperstepper** [comment]
I just refactored and it passed u under 10 seconds 10 times in a row on my machine (but I could have just got a good run of rpc latency) hopefully that suffices.

**Comment by pepperstepper** [comment]
I was trying to bundle the mino balanceOf calls with the sMino balanceOf calls by re uising the Multicaller object, but it seemed to be overwriting the first set of calls anyway.

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
