### PR TITLE
[planet-finance] UPDATE_VOTING-STRATEGY

### PR DESCRIPTION
**Pull request by ash-greninja-poke**
Fixes # .

Changes proposed in this pull request:
- REMOVED OLD POOLS SHARES
- ADDED LENDING POOL
- ADDED TWO NEW POOLS

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
@ash-greninja-poke It is throwing this error:
```
    call revert exception (method="getAccountSnapshot(address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.0)

      at Logger.Object.<anonymous>.Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Logger.Object.<anonymous>.Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
      at Interface.Object.<anonymous>.Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:425:23)
      at node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:2248:40
          at Array.map (<anonymous>)
      at Object.<anonymous> (node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:2247:51)
      at step (node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:80:23)
      at Object.next (node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:61:53)
      at fulfilled (node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:51:58)
```

**Comment by ash-greninja-poke** [comment]
@ChaituVR Can you check it now?

**Comment by ash-greninja-poke** [comment]
@ChaituVR would you please merge it now?

**Comment by planetfinance** [comment]
hey @ChaituVR why was the merge blocked?

What do we need to do to finalize this, our community is waiting on this to be able to vote accurately.

**Review by bonustrack — APPROVED** [review]

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
