### PR TITLE
[aavegotchi-agip] Update Aavegotchi Strategy

### PR DESCRIPTION
**Pull request by cinnabarhorse**
Fixes # .

Changes proposed in this pull request:
- Add new wearables to fix broken strategy
- 
-

### CODE REVIEW

**Comment by ChaituVR** [comment]
@cinnabarhorse conflicts

**Comment by cinnabarhorse** [comment]
Thanks, fixed! @ChaituVR

**Comment by ChaituVR** [comment]
@cinnabarhorse Looks like there is an active proposal https://snapshot.org/#/aavegotchi.eth/proposal/0x2a4a3871f300701c734d4d3b6dc139dc161d1f7c7c5c7eab974158d85b393e46 if this can effect voting power, then some users may see wrong voting power due to our cache systems

**Comment by cinnabarhorse** [comment]
> @cinnabarhorse Looks like there is an active proposal https://snapshot.org/#/aavegotchi.eth/proposal/0x2a4a3871f300701c734d4d3b6dc139dc161d1f7c7c5c7eab974158d85b393e46 if this can effect voting power, then some users may see wrong voting power due to our cache systems

The current proposal is not fully reflecting everyone's accurate voting power due to a bug that this PR fixes. Can we merge it and I will have our community re-vote, instead of re-submitting the prop. 

If the issue still isn't fixed then I will just have the poster re-submit the prop.

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
