### PR TITLE
[reliquary] Adapt strategy for new contract code

### PR DESCRIPTION
**Pull request by franzns**
Adapts to changes in new Reliquary contract code.

Changes proposed in this pull request:
- Change in ABI, adapt code accordingly
- Change of naming allocation points -> multiplier

### CODE REVIEW

**Comment by ChaituVR** [comment]
@0xSkly Can take a look?

**Comment by 0xSkly** [comment]
looks good @ChaituVR ,  @franzns took over maintenance of the snapshot strategy, maybe we can add him as additional author?

**Comment by ChaituVR** [comment]
@0xSkly Awesome. Thanks for confirming, can add a comment beside line 6? :)

May be like `export const author = '0xSkly'; // coAuthor = 'franzns'`

**Comment by franzns** [comment]
> @0xSkly Awesome. Thanks for confirming, can add a comment beside line 6? :)
> 
> May be like `export const author = '0xSkly'; // coAuthor = 'franzns'`

I added the line :) thanks!

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
