### PR TITLE
[galaxy-nft-with-score] Add matic support and switch subgraphs

### PR DESCRIPTION
**Pull request by alberthaotan**
Feat: [galaxy-nft-with-score] Add matic support and switch subgraphs

### CODE REVIEW

**Comment by ChaituVR** [comment]
@alberthaotan Can this affect the voting power of previous proposals? If so it would be better to create a new strategy with `-v2` as this strategy is being used by 3 different spaces

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Also, this strategy takes longer than 20 secs when we pass 500 addresses, you can test this in your local using:
```
npm test --strategy=galaxy-nft-with-score --more=500
```

**Review by ChaituVR — CHANGES_REQUESTED** [review]
From the previous comment:
@alberthaotan Can this affect the voting power of previous proposals? If so it would be better to create a new strategy with -v2 as this strategy is being used by 3 different spaces

**Comment by alberthaotan** [comment]
Hi, Chaitanya. Thanks for your review. This change is to switch to new subgraph and won't affect previous results. Also, 3 spaces that use this strategy are just testing , so should be safe to ignore them.

**Comment by ChaituVR** [comment]
Thanks for confirming @alberthaotan  :)

**Review by bonustrack — APPROVED** [review]

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
