### PR TITLE
[contract-call-view] Add `contract-call-view` Strategy

### PR DESCRIPTION
**Pull request by tkowalczyk**
Changes proposed in this pull request:
- [Discord Ticket-1779](https://discord.com/channels/707079246388133940/1192142871445377105)
- This strategy allows to call functions which returns multiple values instead of one like `contract-call`

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @tkowalczyk `contract-call` strategy already accepts a param `output`

**Comment by tkowalczyk** [comment]
@ChaituVR you are right but `contract-call` do not support functions which returns more than one value as output, in this strategy you are able to provide index of returned value and use this one.

**Comment by ChaituVR** [comment]
@tkowalczyk Could you add a new param on `contract-call` itself?

**Comment by tkowalczyk** [comment]
@ChaituVR to be honest it will require to rewrite the `contract-call` strategy and also adjust tests for it so I would prefer to stay with proposed in this PR solution in separate strategy, would it be possible or rewrite the `contract-call` strategy is the prefered solution?

**Comment by ChaituVR** [comment]
@tkowalczyk Did you try something like [here](https://snapshot.org/#/playground/contract-call?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4NWNBMEYzM2YxZWJEMTQwZGVmODc3MjEyOTFGRjMxM0E5MTQxRjc5ZSIsInN5bWJvbCI6IkNha2UiLCJkZWNpbWFscyI6MTgsIm91dHB1dCI6IjEiLCJtZXRob2RBQkkiOnsiaW5wdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6IiIsInR5cGUiOiJhZGRyZXNzIn1dLCJuYW1lIjoidXNlckluZm8iLCJvdXRwdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6Imxhc3RTdGFrZVRpbWUiLCJ0eXBlIjoidWludDI1NiJ9LHsiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJhbW91bnQiLCJ0eXBlIjoidWludDI1NiJ9LHsiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJ3YWl0aW5nUmV3YXJkcyIsInR5cGUiOiJ1aW50MjU2In1dLCJzdGF0ZU11dGFiaWxpdHkiOiJ2aWV3IiwidHlwZSI6ImZ1bmN0aW9uIn19LCJuZXR3b3JrIjoiNDIxNjEiLCJzbmFwc2hvdCI6IjE2Njc3NzAzNiIsImFkZHJlc3NlcyI6WyIweGY3OTBiODBCNTYyRWFCMGMxNzE4MWM2MzdhNDczOGExN2UzMzkyNTUiLCIweDBBQzYzNWQ1MDRjNjc5NUY1MDgxMDZmNTI4RDYwOGQ5MTdBNjkwMjIiLCIweGM4NDYyMmMwMjU3RWM3OTVENDI0MDdhOTEzRTZGNEViQTc3OTQ1NTAiXX0.)

**Comment by tkowalczyk** [comment]
@ChaituVR , Yes of course...

I am not able to deal with contract-call with function which return more than 1 value in the response:

```
https://snapshot.org/#/playground/contract-call?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4NWNBMEYzM2YxZWJEMTQwZGVmODc3MjEyOTFGRjMxM0E5MTQxRjc5ZSIsIm1ldGhvZEFCSSI6eyJpbnB1dHMiOlt7ImludGVybmFsVHlwZSI6ImFkZHJlc3MiLCJuYW1lIjoiIiwidHlwZSI6ImFkZHJlc3MifV0sIm5hbWUiOiJ1c2VySW5mbyIsIm91dHB1dHMiOlt7ImludGVybmFsVHlwZSI6InVpbnQyNTYiLCJuYW1lIjoibGFzdFN0YWtlVGltZSIsInR5cGUiOiJ1aW50MjU2In0seyJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6ImFtb3VudCIsInR5cGUiOiJ1aW50MjU2In0seyJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6IndhaXRpbmdSZXdhcmRzIiwidHlwZSI6InVpbnQyNTYifV0sInN0YXRlTXV0YWJpbGl0eSI6InZpZXciLCJ0eXBlIjoiZnVuY3Rpb24ifX0sIm5ldHdvcmsiOiI0MjE2MSIsInNuYXBzaG90IjoiMTY2NzAzMzc0IiwiYWRkcmVzc2VzIjpbIjB4OGNmZDJjZWE2ZDU3MzEzYzMyZjlkOTc5NWQ5ODQwZmEyMzE2NTcwOCJdfQ..
```

and when I specify only one return value I got the value but for the first one not the one I provide

```
https://snapshot.org/#/playground/contract-call?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4NWNBMEYzM2YxZWJEMTQwZGVmODc3MjEyOTFGRjMxM0E5MTQxRjc5ZSIsIm1ldGhvZEFCSSI6eyJpbnB1dHMiOlt7ImludGVybmFsVHlwZSI6ImFkZHJlc3MiLCJuYW1lIjoiIiwidHlwZSI6ImFkZHJlc3MifV0sIm5hbWUiOiJ1c2VySW5mbyIsIm91dHB1dHMiOlt7ImludGVybmFsVHlwZSI6InVpbnQyNTYiLCJuYW1lIjoiYW1vdW50IiwidHlwZSI6InVpbnQyNTYifV0sInN0YXRlTXV0YWJpbGl0eSI6InZpZXciLCJ0eXBlIjoiZnVuY3Rpb24ifX0sIm5ldHdvcmsiOiI0MjE2MSIsInNuYXBzaG90IjoiMTY2NzE0OTg2IiwiYWRkcmVzc2VzIjpbIjB4OGNmZDJjZWE2ZDU3MzEzYzMyZjlkOTc5NWQ5ODQwZmEyMzE2NTcwOCJdfQ..
```

obraz

**Comment by ChaituVR** [comment]
For the playgrounds links you have provided, try adding `output` property

where you get more than one output: 
https://snapshot.org/#/playground/contract-call?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4NWNBMEYzM2YxZWJEMTQwZGVmODc3MjEyOTFGRjMxM0E5MTQxRjc5ZSIsIm91dHB1dCI6IjEiLCJtZXRob2RBQkkiOnsiaW5wdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6IiIsInR5cGUiOiJhZGRyZXNzIn1dLCJuYW1lIjoidXNlckluZm8iLCJvdXRwdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6Imxhc3RTdGFrZVRpbWUiLCJ0eXBlIjoidWludDI1NiJ9LHsiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJhbW91bnQiLCJ0eXBlIjoidWludDI1NiJ9LHsiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJ3YWl0aW5nUmV3YXJkcyIsInR5cGUiOiJ1aW50MjU2In1dLCJzdGF0ZU11dGFiaWxpdHkiOiJ2aWV3IiwidHlwZSI6ImZ1bmN0aW9uIn19LCJuZXR3b3JrIjoiNDIxNjEiLCJzbmFwc2hvdCI6IjE2NjcwMzM3NCIsImFkZHJlc3NlcyI6WyIweDhjZmQyY2VhNmQ1NzMxM2MzMmY5ZDk3OTVkOTg0MGZhMjMxNjU3MDgiXX0.

**Comment by tkowalczyk** [comment]
> For the playgrounds links you have provided, try adding `output` property
> 
> where you get more than one output: https://snapshot.org/#/playground/contract-call?query=eyJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4NWNBMEYzM2YxZWJEMTQwZGVmODc3MjEyOTFGRjMxM0E5MTQxRjc5ZSIsIm91dHB1dCI6IjEiLCJtZXRob2RBQkkiOnsiaW5wdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJhZGRyZXNzIiwibmFtZSI6IiIsInR5cGUiOiJhZGRyZXNzIn1dLCJuYW1lIjoidXNlckluZm8iLCJvdXRwdXRzIjpbeyJpbnRlcm5hbFR5cGUiOiJ1aW50MjU2IiwibmFtZSI6Imxhc3RTdGFrZVRpbWUiLCJ0eXBlIjoidWludDI1NiJ9LHsiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJhbW91bnQiLCJ0eXBlIjoidWludDI1NiJ9LHsiaW50ZXJuYWxUeXBlIjoidWludDI1NiIsIm5hbWUiOiJ3YWl0aW5nUmV3YXJkcyIsInR5cGUiOiJ1aW50MjU2In1dLCJzdGF0ZU11dGFiaWxpdHkiOiJ2aWV3IiwidHlwZSI6ImZ1bmN0aW9uIn19LCJuZXR3b3JrIjoiNDIxNjEiLCJzbmFwc2hvdCI6IjE2NjcwMzM3NCIsImFkZHJlc3NlcyI6WyIweDhjZmQyY2VhNmQ1NzMxM2MzMmY5ZDk3OTVkOTg0MGZhMjMxNjU3MDgiXX0.

Sorry but I dont get it, link that you have provided does not work, what do you mean by adding `output` property it is not supported by `contract-call` strategy, it support functions which returns only ONE value in output

**Comment by ChaituVR** [comment]
I mean like this: 
```JSON
{
  "address": "0x5cA0F33f1ebD140def87721291FF313A9141F79e",
  "output": "1",
  "methodABI": {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "userInfo",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "lastStakeTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "waitingRewards",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
}
```

**Comment by tkowalczyk** [comment]
It looks ok

**Comment by ChaituVR** [comment]
Thanks for testing @tkowalczyk it is just to avoid similar strategies :) hope you understand, so closing this PR for now. feel free to reopen if you need it

**Pull request closed without merging**
