### PR TITLE
[arrow-vesting] Update Arrow-Vesting strategy to only count vested, unclaimed tokens

### PR DESCRIPTION
**Pull request by bghughes**
Previously this strategy counted all tokens sitting on a vesting contract, including claimed ones. This led to weird behaviors and double counting. The Arrow community tasked me with iterating this strategy to **only count vested Arrow that can be claimed but is unclaimed.** This way, used with the `balanceOf` ERC20 strategy in voting, the snapshots will allow members to vote their vested Arrow, even if unclaimed, and there won't be incorrect accounting regarding stake on votes.

Shoutout to @daoio for the help.

Changes proposed in this pull request:
- Change arrow-vesting strategy to only count `unclaimed` Arrow tokens in a vesting contract

### CODE REVIEW

**Comment by bghughes** [comment]
For your review too @thomasg who is the project admin

**Comment by ChaituVR** [comment]
Tagging @BrassLion as he is the author of the strategy

**Comment by ChaituVR** [comment]
There are two active proposals that use this strategy, better to wait until they are closed, or even better if we can just create a new strategy

https://snapshot.org/#/arrowair.eth/proposal/0xb8ec567d58521249365c2c6637ef6595c0ae4e6e9166e50d7dd07328f9777040
https://snapshot.org/#/arrowair.eth/proposal/0xc72c11d8cb5c83806d348872e9f7ee2a848cf9a4b8837c8d77a87fc7032e4661

**Review by BrassLion — APPROVED** [review]
LGTM. I had a quick look at the new strategy and the logic makes sense to me.

**Comment by ChaituVR** [comment]
@thomasgarrison Does it change the voting power of existing voters?

**Comment by thomasgarrison** [comment]
Yes. This is fixing a bug where voting power is being double counted if a voter has claimed $ARROW from a vesting contract. This is just now becoming an issue as cliffs have been reached. If that's problematic we can wait until the last proposal is done voting. I've asked everyone not to post any more proposals until this is merged in

**Review by ChaituVR — APPROVED** [review]
I see no open proposals now, so merging, Thanks for waiting ❤️

**Pull request merged**
