### PR TITLE
[hopr-staking] Hopr staking

### PR DESCRIPTION
**Pull request by QYuQianchen**
[As suggested](https://github.com/snapshot-labs/snapshot-strategies/pull/74#pullrequestreview-760466694) by @ChaituVR, this PR contains only one strategy: hopr-staking.

This strategy calculates the sum of three variables of HOPR staking smart contract: 
- virtual staking
- actual staking
- rewards - claimed rewards

### CODE REVIEW

**Comment by QYuQianchen** [comment]
@ChaituVR After checking your comment in the other PR #75, I double-checked this one. As this strategy does not use function calls, so it looks okay. Could you please take a look at this PR as well? THX

**Comment by ChaituVR** [comment]
@QYuQianchen Looks good! Thanks for raising separate PRs :) @bonustrack will do a final review soon and these two PRs will be good to merge

**Review by bonustrack — APPROVED** [review]

**Comment by QYuQianchen** [comment]
I think all conflicts are resolved now :D @ChaituVR

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
@QYuQianchen Strategy is live https://snapshot.org/#/strategy/hopr-staking

**Pull request merged**
