### PR TITLE
adding Lodestar Finance strategies

### PR DESCRIPTION
**Pull request by 0xAppo**
Fixes # .

Changes proposed in this pull request:
- Adding strategies for Lodestar Finance

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
@0xAppo Looks like there are conflicts, also make sure you are changing files related your strategy only

**Comment by LodestarFinance** [comment]
My mistake on the change to contract-call, must have accidentally auto formatted the examples.json file by accident. Also resolved the conflicts in index.ts.

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @0xAppo Please create separate PRs for each strategy, It will easy to review/integrate/maintain

**Comment by ChaituVR** [comment]
Closing as stale, please reopen if needed

**Pull request closed without merging**
