### PR TITLE
[safe-vested] Optimize Strategy: safe-vested 

### PR DESCRIPTION
**Pull request by cristovaoth**
### Summary
This PR improves calculation complexity, making the strategy faster:

- **Allocations Map**: Builds an allocations map in memory once (takes approximately 50ms).
- **Efficient Lookups**: Use the map for retrieving allocations during calculations. For 5000+ addresses, this reduces execution time by around 20 seconds.
- **Optimised Result Construction**: Avoids creating new objects at every step of the result reducer, using simple assignment instead. For +5000 addresses, this saves around 7 seconds.

### Discussion
An additional optimization to discuss with the SAFE team involves the size of the allocations file, currently around 120MB and loaded each time the strategy runs. We were able to trimmed it to approximately 17MB. Two possible options to optimize this:
1. Source the trimmed file alongside the strategy.
2. Make the trimmed file available at http:/safe-claiming-app

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @cristovaoth Tests are failing, could you please take a look, try running `yarn test --strategy=safe-vested` in your local. looks like example.json is missing addresses that have voting power

**Comment by cristovaoth** [comment]
Hey @ChaituVR 

I've included one address with voting power, which fixes all the tests locally except for the one related to slowness. This issue is being addressed in this PR.

We are currently consulting with the SAFE team to confirm whether it is acceptable for them to source the trimmed allocations JSON file next to the strategy.

Would this be acceptable for Snapshot? The file will be approximately 17 MB.

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
> We are currently consulting with the SAFE team to confirm whether it is acceptable for them to source the trimmed allocations JSON file next to the strategy.

> Would this be acceptable for Snapshot? The file will be approximately 17 MB.

Hi @cristovaoth Sounds like a big file but you can add it if it is important :) 

or alternate way is to call it only once and store it in a global variable ([before strategy function](https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/safe-vested/index.ts#L37)) if JSON is available we can just reuse and if not we will fetch it again

**Comment by cristovaoth** [comment]
Hi @ChaituVR , I agree. I think global variable would be a better approach, especially because SAFE people retain control over the datasource. However, this requires that your services are long-lived (serverless lambdas wouldn't be suitable).

If all is a go, I will address this in a follow up PR

**Comment by cristovaoth** [comment]
Just created a subsequent PR

**Pull request merged**
