### PR TITLE
AMKT [amkt]

### PR DESCRIPTION
**Pull request by RatanRSur**
Opening this as a way to get feedback on what is pretty close to the PR we're ultimately going to create.

I noticed there wasn't any non-delegative QV so I went ahead and created that.

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
HI @RatanRSur Looks good but instead of these strategies in your space you can try using [`math`](https://snapshot.org/#/strategy/math) strategy  with `square-root` and `multiply` operations, let me know if it doesn't work as expected :)

**Comment by RatanRSur** [comment]
Sure, I can try that. For my curiosity, what is the benefit to using a strategy as opposed to the basic operators/Math library directly?

**Comment by RatanRSur** [comment]
Hey! I used the math strategy and removed the new quadratic balance of strategy I had added. Let me know if you'd still like me to use math for the multiplication as well. I saw that it wouldn't reduce code elsewhere and make the code in this strategy harder to read so I wanted to get your opinion on that before I made that change.

**Comment by ChaituVR** [comment]
It is easy to maintain, Reduces duplicate code, also helps users understand that it just does `math` and not any complex calculation

**Comment by JamesEBall** [comment]
@ChaituVR The proposed changes have been implemented, could we get this reviewed?

**Comment by JamesEBall** [comment]
Hi @ChaituVR we have reviewed the changes proposed.

**Comment by ChaituVR** [comment]
Hey, @RatanRSur @JamesEBall You still need this?

**Comment by RatanRSur** [comment]
Yup! I'll be updating it very soon.

**Comment by RatanRSur** [comment]
Hey! Would love your eyes on this again.

One thing to note is that we will need to change the AMKT address at some point but we need it to point to the current address for testing purposed.

**Comment by ChaituVR** [comment]
@RatanRSur Hey, i still feel like you can use [math](https://snapshot.org/#/strategy/math) strategy for this. you tried it?

**Comment by ChaituVR** [comment]
@RatanRSur Yes yes but you can use the `math` strategy in your space directly and use the `multiply` operation. (I mean no need of a separate strategy for this) Try and let me know :)

**Comment by RatanRSur** [comment]
Oh! As in don't even submit a PR.

**Comment by RatanRSur** [comment]
Great. I'm trying that now but I'm getting some issues. Will ask for help on the discord.

**Pull request closed without merging**
