### PR TITLE
[iotex-balance] change IOTEX server URI

### PR DESCRIPTION
**Pull request by maswalker**
Changes proposed in this pull request:
- change iotex server uri

### CODE REVIEW

**Comment by maswalker** [comment]
@ChaituVR

**Review by bonustrack — APPROVED** [review]

**Comment by guo** [comment]
@ChaituVR Could you please help merge this PR? There is vote ongoing that requires this change to unblock. Thanks!

**Comment by ChaituVR** [comment]
@maswalker @guo changes should be live by now

**Comment by guo** [comment]
Thank you for the prompt review and merge!

**Pull request merged**
