### PR TITLE
[spacefi-blp-nft] add blp-nft strategy

### PR DESCRIPTION
**Pull request by SpaceFinance**

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @SpaceFinance You can use `contract-call` strategy on your space for this :) can try?

**Comment by SpaceFinance** [comment]
> 你好@SpaceFinance`contract-call`您可以为此在您的空间上使用策略:)可以尝试吗？

image
I have attempted to run the test and passed it.

**Comment by ChaituVR** [comment]
I mean you don't need a separate strategy, you can use existing strategy

**Comment by SpaceFinance** [comment]
> 我的意思是你不需要单独的策略，你可以使用现有的策略

After discussion, it seems that two strategies are necessary. Please check ticket-1915

**Comment by SpaceFinance** [comment]
> I mean you don't need a separate strategy, you can use existing strategy

https://discord.com/channels/707079246388133940/1199692877844971670
Based on the discussion, I need two different strategies, please check

**Comment by SpaceFinance** [comment]
> I mean you don't need a separate strategy, you can use existing strategy

According to the discussion, I need two different strategies, please check ticket-1915

**Comment by ChaituVR** [comment]
Closing after discussion on discord, feel free to reopen or create new PR if required

**Pull request closed without merging**
