### PR TITLE
[math] Implement divide in MATH strategy

### LINKED ISSUE #1200: MATH strategy does not offer complete functionality
### Expected behavior

MATH strategy should allow all common mathematical operations

### Actual behavior

MATH strategy does not support division

### Steps to reproduce the behavior

Try using division with MATH strategy

NOTE: found out that there is good reason not to include addition, revised to just add division support

### PR DESCRIPTION
**Pull request by 0xAurelius**
Fixes #1200 

Changes proposed in this pull request:
- Add support for division to MATH strategy

### CODE REVIEW

**Comment by ChaituVR** [comment]
Hi @0xAurelius There is a reason why we didn't add `add` to the math strategy, it is because normally  if space is having `5` strategies, the result will be the sum of those `5` strategies

And then we have a limit of `8` strategies per space, if we have `add`, users will use this to bypass that rule to include more strategies😅

**Comment by 0xAurelius** [comment]
The use-case we have in mind is actually for permissioning proposal creation based on the total voting power a user has in the space - not summing up voting power for proposal voting

Since we have 5 sources of voting power, we want to allow someone to post a proposal if they have a total number of tokens above some threshold

Could we somehow limit this to proposal creation? Or does proposal creation support summing up the way they normal voting power strategies do?

Divide alone would help us anyway, happy to reduce to just that in this PR

**Comment by ChaituVR** [comment]
Got it, makes sense why you added it, but we now have [proposal validation](https://docs.snapshot.org/user-guides/strategies/validation-strategies#proposal-validation-in-space-settings) now, try to setup this in your space, with basic validation I, it checks if you have that sum of voting power from strategies defined to create a proposal or not :) let me know if you face some issues doing so, 

But yea, happy to merge the divide one :)

**Comment by 0xAurelius** [comment]
OK great, I just updated this PR to only add a `divide` operation

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
