### PR TITLE
[swapr] fix: update Swapr Arbitrum One subgraph endpoint

### PR DESCRIPTION
**Pull request by adamazad**
# Summary

Updates the Swapr Arbitrum One subgraph endpoint to the most recent one.

### CODE REVIEW

**Comment by ChaituVR** [comment]
@luzzif can you confirm this change?

**Comment by ChaituVR** [comment]
Ok I see an issue with swapr-arbitrum-one-v3

**Review by ChaituVR — APPROVED** [review]

**Comment by adamazad** [comment]
@ChaituVR thank you!

**Comment by ChaituVR** [comment]
Thanks for the patience @adamazad :)

**Pull request merged**
