### PR TITLE
[ogn] Update OGN strategy for new series staking

### PR DESCRIPTION
**Pull request by mikeshultz**
We (Origin Protocol) recently moved from our old legacy staking to a new staking contract.  This updates the calls required for it, the addresses in `example.json`, and a minor verbiage change.

Changes proposed in this pull request:
- Update `ogn` strategy to utilize new staking system, removing support for the old

### CODE REVIEW

**Review by ChaituVR — CHANGES_REQUESTED** [review]
Hi @mikeshultz I see two open proposals on `origingov.eth` space, we should wait until those are closed/archived. else better to create a new strategy :)

**Comment by mikeshultz** [comment]
The timing was kind of unfortunate. I think we'd like to merge this anyway
if we can and it shouldn't cause any issues like double votes. Let me know
if your request is a requirement to get this merged.

**Comment by mikeshultz** [comment]
@ChaituVR We've gone ahead and deleted the proposals.  Hopefully we can get this merged so we can put them back up?

**Comment by ChaituVR** [comment]
Thank you @mikeshultz sorry for not noticing before. I just need a confirmation from author @franckc would be great if you can change author to your org GitHub so we can merge the changes coming from there

**Comment by ChaituVR** [comment]
Oh i see you both are in same org and proposals are deleted, i will merge this then

**Review by ChaituVR — APPROVED** [review]

**Comment by mikeshultz** [comment]
Thanks for the quick turnaround today, @ChaituVR.  We appreciate it.  How long until this is deployed/usable?

**Comment by mikeshultz** [comment]
Nevermind, looks like it's working, thanks again.

**Pull request merged**
