### PR TITLE
[aavegotchi-agip] Aavegotchi

### PR DESCRIPTION
**Pull request by cinnabarhorse**
Fixes # .

Changes proposed in this pull request:
- Add new wearable IDs 
- Update tests

### CODE REVIEW

**Comment by ChaituVR** [comment]
I see a few active proposals on aavegotchi space
if we merge this those will be affected
better to wait until those proposals are closed

**Comment by cinnabarhorse** [comment]
The active proposals are likely to fail due to lack of quorum, because they are affected by the issue this PR fixes. @ChaituVR

**Comment by cinnabarhorse** [comment]
Please merge if you don't see any other issues, thanks!

**Comment by ChaituVR** [comment]
But users already voted may have old voting power while new ones will have new voting power 😅

**Comment by cinnabarhorse** [comment]
But the VP will only increase, will not decrease @ChaituVR

**Comment by ChaituVR** [comment]
If we update the voting strategy the users that already voted on current proposals will keep the same voting power but new ones will have voting power based on the updated strategy

It can cause a lot of confusion

**Comment by ChaituVR** [comment]
You think you can communicate this information to users?

**Comment by cinnabarhorse** [comment]
Yes we will communicate the update in our DAO channel. 

If users that have already voted vote again, will the VP be updated?

**Comment by ChaituVR** [comment]
Not by default, but if we remove cache then if users vote again, VP will be updated.

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
@cinnabarhorse we just flushed the cache, make sure to communicate with your users to vote again :)

**Pull request merged**
