### PR TITLE
Setup MemberRewards for GoldfinchVotingPower [goldfinch-voting-power]

### PR DESCRIPTION
**Pull request by gregegan**
Add's a Goldfinch MembershipRewards check to see votingPower of GFI locked in vaults.

### CODE REVIEW

**Review by CarterAppleton — APPROVED** [review]
nice this looks good to me

**Review by ChaituVR — CHANGES_REQUESTED** [review]
@sanjayprabhu @warbler-labs Can approve these changes?

**Review by ChaituVR — CHANGES_REQUESTED** [review]
@gregegan Some tests are failing, can try to run in your local?

**Review by sanjayprabhu — APPROVED** [review]
Looks good to me.

**Review by ChaituVR — APPROVED** [review]

**Pull request merged**
