### PR TITLE
[polygon-self-staked-pol] New strategy: polygon-self-staked-pol

### PR DESCRIPTION
**Pull request by xavikh**
This strategy calculates the voting power based on the active stake of delegators for the Polygon network

### CODE REVIEW

**Comment by xavikh** [comment]
I see the strategy is taking more than 20s to run for 500 addresses. I'm trying to look for a different solution.

**Comment by ChaituVR** [comment]
> I see the strategy is taking more than 20s to run for 500 addresses. I'm trying to look for a different solution.

It should be fine for now. I will merge it but feel free to modify if you have any idea to optimize :)

**Review by ChaituVR — APPROVED** [review]

**Comment by ChaituVR** [comment]
Looks like https://github.com/aragon/polygon-snapshot-strategy/blob/e003689b5743f0f74dc56fa92adacb04bf710079/src/strategies/polygon-self-staked-pol/index.ts#L39 will not scale well if `nftCounter` returns a high value

**Comment by xavikh** [comment]
Yes, we are considering a different solution with an wrapper contract that aggregates the Vp. That might reduce the strategy to a simple contract call.

**Pull request merged**
